trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true
    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      displayName: 'Install dependencies'
    - script: |
        echo "Building the project..."
        # Add commands to build your project here
        python -m py_compile Greetings.py
      displayName: 'Build'

- stage: Test
  jobs:
  - job: TestJob
    steps:
    - script: |
        echo "Running tests..."
        # Add commands to test your project here
        # For example, if you had tests, you could run them with pytest
        # pytest
      displayName: 'Test'

- stage: Deploy
  jobs:
  - job: DeployJob
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    steps:
    - script: |
        echo "Deploying to staging environment..."
        # Add your deployment scripts here
        # For example, this could be a script to deploy to Azure App Service
        # az webapp up --name <app_name> --resource-group <resource_group>
      displayName: 'Deploy to staging'
