trigger:
- main

pool:
  vmImage: 'windows-latest'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true
    - script: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      displayName: 'Install dependencies'
    - script: |
        echo "Compiling Python code..."
        python -m py_compile Greetings.py
      displayName: 'Compile Python script'

- stage: Test
  jobs:
  - job: TestJob
    steps:
    - script: |
        echo "Running tests..."
        # If you have tests written with pytest or another framework, run them here
        # pytest
      displayName: 'Run tests'

- stage: Deploy
  jobs:
  - job: DeployJob
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    steps:
    - script: |
        echo "Deploying to staging environment..."
        # Here you would include a script that performs the actual deployment
        # For example, this could be an Azure CLI script to deploy to an Azure service
        # Make sure to configure the Azure service connection if you are deploying to Azure
        # az webapp up --name <app_name> --resource-group <resource_group>
      displayName: 'Deploy to staging'
